### ISSUE TITLE
filter is not works

### ISSUE THREAD

**Issue by ariesjia** [krisnye/watchdirectory#1]
i found the filter is not works

**Comment by krisnye** [comment]
Can your provide some more details?

**Comment by ariesjia** [comment]
Thank you for your reply

The doc says options have 'fiter' , but it not works，even not perform the function

At last i search the code . if I use ' include '  insead of ' filter ' , it can meet my needs .

this is my options, i just want ignore files that begin with "." or root directory

{include:function(file){
        var fileList = file.split('/');
        return fileList[fileList.length-1][0] != '.' && fileList[fileList.length-1] !='';
}}

**Comment by krisnye** [comment]
Ok, I need to update the docs since the new properties are 'include' and/or 'exclude'
